import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export const metadata = {
  title: "Job-Chain",
  description: "Generated by create next app",
  icons: {
    icon: "/chain.png",
    shortcut: "/chain.png",
    apple: "/chain.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="h-screen overflow-auto">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
