import "./globals.css";
import LayoutShell from "../components/LayoutShell";

export const metadata = {
  title: "Job-Chain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}
